apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  my.cnf: |
    [mysqld]
    sql_mode=STRICT_TRANS_TABLES
    max_connections=200
    innodb_buffer_pool_size=256M

