apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: <BASE64 code> # Base64 encoded value for 'userinput'
  password:  <BASE64 code> # Base64 encoded value for 'userinput'