apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: nfs  # This should match the PV's storageClassName
  accessModes:
    - ReadWriteMany  # Same as the PV access mode
    # - ReadOnlyMany  # Allows multiple clients to mount the volume as read-only
    # - ReadWriteOnce  # Allows a single client to mount the volume as read-write
  resources:
    requests:
      storage: <Desired capacity>  # This must match or be less than the PV's capacity