apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: <Desired capacity>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Allows multiple clients to mount and write to this volume
  persistentVolumeReclaimPolicy: Retain  # Retain the data when the PVC is deleted
  storageClassName: nfs  # Use this storage class for the PVC
  mountOptions:
    - hard
    - nfsvers=4.1  # NFS version and mount options
  nfs:
    server: <NFS-server hostname>  # Replace with your NFS server's hostname or IP address
    path: <NFS mount dir path>  # The NFS export path on the server

