name: Validate Kubernetes Configs

on:
  pull_request:
    paths:
      - '!**/main.yml'
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install kubeval
        run: |
          curl -s https://api.github.com/repos/instrumenta/kubeval/releases/latest | jq -r '.assets[] | select(.name | test("kubeval-linux-amd64")) | .browser_download_url' | xargs curl -L -o /usr/local/bin/kubeval
          chmod +x /usr/local/bin/kubeval

      - name: Validate Kubernetes YAML files
        run: |
          kubeval *.yml
          kubeval *.yaml
